apiVersion: v1
kind: Service
metadata:
  name: bat-bot-service
  labels:
    app: bat-bot-app
spec:
  ports:
  - port: 80
    name: bat-bot-web
    targetPort: bat-bot-svc
  # clusterIP: None
  selector:
    app: bat-bot-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: by-a-thread-bot-deployment
  namespace: bat-bot
  labels:
    app: bat-bot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bat-bot-app
  template:
    metadata:
      labels:
        app: bat-bot-app
    spec:
      containers:
      - name: by-a-thread-bot
        image: us-west1-docker.pkg.dev/${PROJECT_ID}/bat-bot/bat-bot-app:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8400
          name: bat-bot-svc
        resources:
          limits:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2Gi
          requests:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2Gi
        env:
        - name: DISCORD_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: dc-bat-bot-secrets
              key: discord_bot_token
