apiVersion: v1
kind: ServiceAccount
metadata:
  name: bat-bot-sa
  namespace: bat-bot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: bat-bot
  name: bat-bot-role
rules:
  - apiGroups: ["extensions", ""]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bat-bot-rolebinding
  namespace: bat-bot
subjects:
  - kind: ServiceAccount
    name: bat-bot-sa
roleRef:
  kind: Role
  name: bat-bot-role
  apiGroup: rbac.authorization.k8s.io
